### ISSUE TITLE
Question on data file names and figure labels in paper

### ISSUE THREAD

**Issue by LuciusLan** [DanHardtDK/ellipsisGPT3#2]
Hi, Daneil, I am reading your paper and doing some experiment on other LLMs other than GPT
There's a minor issue that I'd like to confirm with you
For the data you shared, the file names are not matched with that presented in the labels of Figures 2-5 and Table 1 in your paper. 

I presume the following matching from the contents and the description in Table1
Labels of Figures 2-5 - File names
2Sent - 2SentYN.json
1Sent - 1SentYN.json
SubAnt - 1SentSubordYN.json
SubVPE - 1SentAfterYN.json
Backwards - 1SentSubordBackwardsYN.json
2Actions - 2Actions.json

Is this correct?

Thank you for sharing your work and the codes!

**Comment by DanHardtDK** [comment]
Hi Lucius

Glad to hear you are going to try some other models! Sorry there was a mistake in the file names. The ones you list are all correct except 2Actions.json should be 2ActionsYN.json. Should be correct on github now.
Keep me posted!

Thanks

Dan




Daniel Hardt
Associate Professor
Department of Management, Society and Communication
Copenhagen Business School
Dalgas Have 15, 2000 Frederiksberg
office 2V.024  phone +45 41852024


From: LuciusLan ***@***.***>
Date: Tuesday, 8 August 2023 at 15.39
To: DanHardtDK/ellipsisGPT3 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DanHardtDK/ellipsisGPT3] Question on data file names and figure labels in paper (Issue #2)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Hi, Daneil, I am reading your paper and doing some experiment on other LLMs other than GPT
There's a minor issue that I'd like to confirm with you
For the data you shared, the file names are not matched with that presented in the labels of Figures 2-5 and Table 1 in your paper.

I presume the following matching from the contents and the description in Table1
Labels of Figures 2-5 - File names
2Sent - 2SentYN.json
1Sent - 1SentYN.json
SubAnt - 1SentSubordYN.json
SubVPE - 1SentAfterYN.json
Backwards - 1SentSubordBackwardsYN.json
2Actions - 2Actions.json

Is this correct?

Thank you for sharing your work and the codes!

**Comment by LuciusLan** [comment]
Thank you for the reply!

By the way, I notice that in the latest commit, you included config.cfg~ file whose content appears like a valid OpenAI api key, I'm not sure if this is intended, please take a look
